### ISSUE TITLE
Upload Logo

### ISSUE THREAD

**Issue by francesco-vannini** [PiSupply/Pi-Crust#1]
![picrust](https://user-images.githubusercontent.com/16068311/30545301-1a8b2a2e-9c81-11e7-855d-a095cf14262b.png)

**Comment by francesco-vannini** [comment]
Use this thread to add pictures

**Comment by ChristopherRush** [comment]
![picrust-github-banner](https://user-images.githubusercontent.com/1878314/73881658-a1f91900-4858-11ea-9411-dbbc73615e83.png)

**Comment by ChristopherRush** [comment]
![OSHW_mark_UK000022](https://user-images.githubusercontent.com/1878314/95058623-af201d80-06ef-11eb-8d79-5ff0e4649735.png)

**Comment by ChristopherRush** [comment]
![OSHW_mark_UK000021](https://user-images.githubusercontent.com/1878314/95059468-d62b1f00-06f0-11eb-8913-2df7fbbdcf7b.png)

**Comment by ChristopherRush** [comment]
![OSHW_mark_UK000020](https://user-images.githubusercontent.com/1878314/95059621-0a064480-06f1-11eb-8b09-af70f66b7b5c.png)
